### PR TITLE
updated patch for ruby-2.2.4

### PR DESCRIPTION
**Pull request by ferdinandrosario**

### CODE REVIEW

**Comment by technion** [comment]
Hi,
Unfortunately I'm going to need to ask for more than an empty description, on a commit entitled "updated patch", to describe what benefit this patch brings the codebase.

**Comment by ferdinandrosario** [comment]
Hi @technion ruby2.2.4 is the latest patch for 2.2.x series so I just updated from 2.2.3 to 2.2.4 in which we can ensure that we are always compatible with latest patch

**Comment by technion** [comment]
Hi,

I appreciate the intent to test against the latest release. However, a commit message becomes a permanent record of the change made, and "update patch" is very vague.

If you could change your commit to ensure it refers to the Ruby version the CI environment is run against I can pull it in.

**Comment by ferdinandrosario** [comment]
I changed the commit message. Is there anything else i should do?

**Comment by ferdinandrosario** [comment]
:+1:

**Comment by technion** [comment]
Thank you for this patch and addressing the concerns raised.

**Comment by ferdinandrosario** [comment]
:smile: :raised_hands:

**Pull request merged**
